# Generated by Django 6.0 on 2026-01-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='pimage',
            field=models.ImageField(default='Default.jpg', upload_to='cart_products/'),
        ),
    ]
